#!/bin/bash
set -e

limit=10

is_interactive=0

filtered_prs_query=''

requested_prs_query='is:open is:pr review-requested:@me'

created_prs_query='is:open is:pr author:@me'

mentioned_prs_query='is:open is:pr mentions:@me'

show_help() {
  cat <<-EOF
  Show pull requests list

USAGE
  $ gh prs [flags]

FLAGS
  -r, --requested   Filter by review requested to others
  -c, --created     Filter by created to me 
  -m, --mentioned   Filter by mentioned to me
  -l, --limit       Maximum number of items to fetch (default 10)
  -h, --help        Show help

EXAMPLES
  $ gh prs
  $ gh prs -r
  $ gh prs -c
  $ gh prs -m
EOF
}

show_search_prs() {
  local query='
  query ($q: String!, $limit: Int = 10) {
    search(first: $limit, type: ISSUE, query: $q) {
      nodes {
        ... on PullRequest {
          number
          title
          url
          updatedAt
          repository {
            nameWithOwner
          }
        }
      }
    }
  }
  '

  local template='
{{- range $pr := .data.search.nodes -}}
  {{- printf "#%v\t%s\t%s\t%s\n" .number .title .repository.nameWithOwner .updatedAt -}}
{{- end -}}

{{ if eq (len .data.search.nodes) 0 }}
{{- printf "No pull requests match your filter" -}}
{{ end }}
'

  gh api graphql -F q="$1" -F limit="$limit" -f query="$query" --template="$template"
}

show_filtered_prs() {
  local query='
  query ($q: String!, $limit: Int = 10) {
    search(first: $limit, type: ISSUE, query: $q) {
      nodes {
        ... on PullRequest {
          number
          title
          url
          updatedAt
          repository {
            name
            nameWithOwner
          }
        }
      }
    }
  }
  '

  local template='
{{ range $pr := .data.search.nodes }}
{{ tablerow (printf "#%v" .number | autocolor "green") (.repository.nameWithOwner) (truncate 40 .title) (.updatedAt | timeago | autocolor "white")  }}
{{ end }}

{{ if eq (len .data.search.nodes) 0 }}
{{- printf "No pull requests match your filter" -}}
{{ else }}
{{ tablerender }}
{{ end }}
'

# local template='{{- if eq (len .data.search.nodes) 0 -}}
# {{- printf "No pull requests match your filter" -}}
# {{- else -}}
# {{- range $pr := .data.search.nodes -}}
# {{- printf "#%v\t%s\t%s\t%s\n" .number (.title | truncate 40) .url (.updatedAt | timeago) -}}
# {{- end -}}
# {{- end -}}'

  gh api graphql -F q="$1" -F limit="$limit" -f query="$query" --template="$template"  | column -t -s$'\t'
}

show_prs() {
  local query='
  fragment pr on PullRequest {
    ... on PullRequest {
      number
      title
      url
      updatedAt
      repository {
        name
      }
    }
  }

  query ($createdPRQuery: String!, $requestedPRQuery: String!, $mentionedPRQuery: String!, $limit: Int = 10) {
    createdPR: search(first: $limit, type: ISSUE, query: $createdPRQuery) {
      nodes {
        ...pr
      }
    }
    requestedPR: search(first: $limit, type: ISSUE, query: $requestedPRQuery) {
      nodes {
        ...pr
      }
    }
    mentionedPR: search(first: $limit, type: ISSUE, query: $mentionedPRQuery) {
      nodes {
        ...pr
      }
    }
  }
  '

  local template='
{{- printf "👀 Review requested pull requests\n\n" | autocolor "magenta+b" -}}

{{- range $pr := .data.requestedPR.nodes -}}
  {{- tablerow (printf "#%v" .number | autocolor "green") (truncate 40 .title) (.url | autocolor "cyan") (.updatedAt | timeago | autocolor "white")  -}}
{{- end -}}

{{ if eq (len .data.requestedPR.nodes) 0 }}
{{- printf "No review requested pull requests\n" -}}
{{ else }}
{{- tablerender -}}
{{ end }}

{{- printf "\n✋ Mentioned pull requests\n\n" | autocolor "magenta+b" -}}

{{- range $pr := .data.mentionedPR.nodes -}}
  {{- tablerow (printf "#%v" .number | autocolor "green") (truncate 40 .title) (.url | autocolor "cyan") (.updatedAt | timeago | autocolor "white")  -}}
{{- end -}}

{{ if eq (len .data.mentionedPR.nodes) 0 }}
{{- printf "No mentioned pull requests\n" -}}
{{ else }}
{{- tablerender -}}
{{ end }}

{{- printf "\n📂 Created pull requests\n\n" | autocolor "magenta+b" -}}

{{- range $pr := .data.createdPR.nodes -}}
  {{- tablerow (printf "#%v" .number | autocolor "green") (truncate 40 .title) (.url | autocolor "cyan") (.updatedAt | timeago | autocolor "white")  -}}
{{- end -}}

{{ if eq (len .data.createdPR.nodes) 0 }}
{{- printf "No created pull requests\n" -}}
{{ else }}
{{- tablerender -}}
{{ end }}
'

  gh api graphql -F createdPRQuery="$created_prs_query" \
    -F requestedPRQuery="$requested_prs_query" \
    -F mentionedPRQuery="$mentioned_prs_query" \
    -F limit="$limit" \
    -f query="$query" \
    --template="$template"
}

search_pr() {
  local result=$(show_filtered_prs "$filtered_prs_query")
  # echo 'hoge'
  # echo -e $result
  # echo 'fuga'
  fzf --ansi <<< "$result"
}

open_browser() {
  local a url b c
  IFS="$(echo -e '\s\s')" read a b url c
  echo $a
  echo $b
  echo $url
  echo $c
  # gh browse "${number#*#}" --repo "$repo_with_owner"
}

while [ $# -gt 0 ]; do
  case "$1" in
  -r|--requested)
    filtered_prs_query="$requested_prs_query"
    ;;
  -c|--created)
    filtered_prs_query="$created_prs_query"
    ;;
  -m|--mentioned)
    filtered_prs_query="$mentioned_prs_query"
    ;;
  -i|--interactive)
    is_interactive=1
    ;;
  -h|--help)
    show_help
    exit 0
    ;;
  -l|--limit)
    limit=$2
    ;;
  esac
  shift
done

if [ -n "$filtered_prs_query" ] ; then
  if [ $is_interactive -eq 1 ] ; then
     search_pr | open_browser
     exit 0
  fi

  show_filtered_prs "$filtered_prs_query"
  exit 0
fi

show_prs
